<a href="https://colab.research.google.com/github/amitgantayat/py_codes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np

In [ ]:
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(list1)
print(arr1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
arr1[2]=50
print(arr1)

[ 1  2 50  4  5]


In [ ]:
arr2=arr1[1:3]

In [ ]:
print(arr1,arr2)

[ 1  2 50  4  5] [ 2 50]


In [ ]:
nlist=[[3,2,5],[6,8,4]]
narr1=np.array(nlist)
print(np.ndim(narr1))
print(np.shape(narr1))
try:
  print(size(narr1))
except:IndexError
print(narr1.size)
print(narr1.dtype)

2
(2, 3)
6
int64


In [ ]:
import re
text = """
Contact us at info@example.com or support@mydomain.org
Call: 9876543210 or 123-456-7890
Meeting on 24/10/2025 and 2025-10-30.
"""
pattern=r'[A-Za-z0-9]+@\w+\.\w{2,}'
print(re.findall(pattern,text))

['info@example.com', 'support@mydomain.org']
